version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      timezone: America/Los_Angeles
      interval: daily
      time: "12:00"
  - package-ecosystem: npm
    directory: /
    schedule:
      timezone: America/Los_Angeles
      interval: daily
      time: "12:00"
